### PR TITLE
Update meta

### PR DESCRIPTION
**Pull request by Cinux90**
Run update-meta-files.sh script.
UPDATE: LICENSE
UPDATE: All Variables by adding prefix wtd_
ADD: doc folder plus files located in it
ADD: .editorconfig and .gitignore

### CODE REVIEW

**Review by dschier-wtd — CHANGES_REQUESTED** [review]
Looks fine, so far:

- Please "git rm tests/test.sh", its an old file, which is no longer needed.

- The variables in defaults/main.yml does not match the README.md. Please update the README.md with a current paste.

**Comment by dschier-wtd** [comment]
One more change please.
The .travis.yml is outdated, too. Please update manually. You have to adjust one line with the correct name by hand.

**Review by dschier-wtd — APPROVED** [review]

**Comment by dschier-wtd** [comment]
Ha ^^ and the new tests are already doing it's thing.
Seems to be a problem with executuion permissions. :(

Can you try to change/update the .travis.yml with:

```
script:
- chmod +x tests/test-ansible.sh
- tests/test-ansible.sh
- chmod +x tests/test-spelling.sh
-  tests/test-spelling.sh
```

Or, if it is ok for you, I can fiddle out the tests and open an issue to ansible-galaxy-skeleton after this.

**Comment by Cinux90** [comment]
Let me fix it here. Then i will open a issue and will fix it in the ansible-galaxy-skeleton

**Comment by dschier-wtd** [comment]
The other stuff made from your side is done from my side and already approved.

**Comment by dschier-wtd** [comment]
yay, testing works: from travis:

```
Examining /home/travis/build/while-true-do/while-true-do.yum-cron/meta/main.yml of type meta
[ANSIBLE0002] Trailing whitespace
/home/travis/build/while-true-do/while-true-do.yum-cron/handlers/main.yml:9
  service: 
[ANSIBLE0002] Trailing whitespace
/home/travis/build/while-true-do/while-true-do.yum-cron/meta/main.yml:18
```

**Comment by dschier-wtd** [comment]
After this change, the first role is refactored completely!

Awesome work, thanks!

**Comment by dschier-wtd** [comment]
yay, green 👍

**Pull request merged**
