### PR TITLE
Fix: dependency in README and meta

### PR DESCRIPTION
**Pull request by dschier-wtd**
Always use the galaxy links, not github.
meta now having the dependency, too.

- Resolves: #6

### CODE REVIEW

**Comment by dschier-wtd** [comment]
blocked from while-true-do.yum
need to work on this first.

**Review by Cinux90 — COMMENTED** [review]
Did not know why, but update-meta-files.sh show now 404 as content ^^'
Rest looks fine

**Comment by dschier-wtd** [comment]
ehem...

**Comment by dschier-wtd** [comment]
and please be more precise with such stuff ^^

example:
```
ds ~/Projekte/while-true-do/while-true-do.yum-cron (fix-deps=) $ cat update-meta-files.sh 
404: Not Found
```

**Comment by dschier-wtd** [comment]
fix is pushed, nevertheless must fix while-true-do.yum first

**Comment by dschier-wtd** [comment]
PR for while-true-do.yum is openend, too.

**Comment by dschier-wtd** [comment]
rebuild triggered in travis.
should work now. yum role is merged.

**Comment by dschier-wtd** [comment]
meh, more to fix.

**Comment by dschier-wtd** [comment]
@donvipre the tests are passing now :)

**Pull request merged**
